name: Hello

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - run: echo "Step next"
      - run: pwd
      - run: python3 ./test.py