name: Hello

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
        with:
	  ref: main
      - run: echo "Hello, world!"
      - run: echo "Step next"
      - run: pwd
      - run: ls -a
      - run: python3 ./test.py